image:
  file: .gitpod.Dockerfile
tasks:
  - init: ls -al /workspace/
  - command: julia -e 'using Pkg; Pkg.add("IJulia"); Pkg.build("IJulia")'
 
ports:
  - name: postgres
    description: data base server
    port: 5432
    visibility: private
    onOpen: ignore

  - name: Web App
    description: The main application web server
    port: 8000
    visibility: public
    onOpen: open-browser

  - name: Web Socket
    description: Web Socket server UI sznching
    port: 8001
    visibility: public
    onOpen: ignore
