image:
  file: .gitpod.Dockerfile
tasks:
  - init: cd .. &&
      echo 'PATH_add /home/gitpod/julia-1.6.5/bin' > .envrc
  #- command: python3 -m http.server 8080 -d docs/build
  #- command: gp preview $(gp url 8080)
  - command: cat db/connectionGITPOD.yml >db/connection.yml
  - command: julia --project=. -i demo.jl
 
ports:
  - name: Web App
    description: The main application web server
    port: 8000
    onOpen: open-browser

  - name: WebSockets
    description: websockets
    port: 8001
    onOpen: notify