image:
  file: .gitpod.Dockerfile
tasks:
  - init: cd .. &&
      echo 'PATH_add /home/gitpod/julia-1.6.7/bin' > .envrc &&
      julia --project=. -i populateDB.jl &&
      julia -e'using Pkg; Pkg.add("Genie");using Genie; Genie.Generator.write_secrets_file()'
  #- command: python3 -m http.server 8080 -d docs/build
  #- command: gp preview $(gp url 8080)
  - command: cat db/connectionGITPOD.yml >db/connection.yml
  - command: julia --project=. -i runWebApp.jl
 
ports:
  - name: postgres
    description: data base server
    port: 5432
    visibility: private
    onOpen: ignore

  - name: Web App
    description: The main application web server
    port: 8000
    visibility: public
    onOpen: open-browser

  - name: Web Socket
    description: Web Socket server UI sznching
    port: 8001
    visibility: public
    onOpen: ignore
