image:
  file: .gitpod.Dockerfile
tasks:
  - init: 
      cat db/connectionGITPOD.yml >db/connection.yml &&
      julia -e'using Genie; Genie.Generator.write_secrets_file(); Pkg.instantiate();include("testsCreateContract.jl")'
  - command: julia --project=. -i runWebApp.jl
 
ports:
  - name: postgres
    description: data base server
    port: 5432
    visibility: private
    onOpen: ignore

  - name: Web App
    description: The main application web server
    port: 8000
    visibility: public
    onOpen: open-browser

  - name: Web Socket
    description: Web Socket server UI sznching
    port: 8001
    visibility: public
    onOpen: ignore
